version: '3.8'

services:
  db:
    container_name: postgresql_container
    image: postgres:15
    ports:
      - "5432:5432"
    platform: linux/amd64  # 플랫폼 지정
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moyeobwayo
    volumes:
      - db_data:/var/lib/postgresql/data  # 데이터베이스 영속성을 위한 볼륨 설정
    restart: always

  backend:
    container_name: moyeobwayo
    build: .
    platform: linux/amd64  # 플랫폼 지정
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/moyeobwayo
      db-username: postgres
      db-password: postgres
    restart: always

volumes:
  db_data: